export const HASTOKEN = 'HASTOKEN';
export const ACCESSTOKEN = 'ACCESSTOKEN';
export const SELCTEDCOUNTRY = 'SELCTEDCOUNTRY';
export const SETUSER = 'SETUSER';
export const LOGOUT = 'LOGOUT';
export const SELCTEDSTORE = 'SELCTEDSTORE';
export const SELCTEDCATEGORY = 'SELCTEDCATEGORY';
export const FCMTOKEN = 'FCMTOKEN';
